#!/bin/sh

#[ -f /usr/local/sbin/igmpproxy ] || exit 0

RETVAL=0
prog="igmpproxy"
PID_FILE="/var/run/igmpproxy.pid" #if the path/file changes, remember to modify snmp checking function
CONFIG_FILE="/var/igmpproxy.conf"
lan_ifname=`config get lan_ifname`
wan_ifname=`config get wan_ifname`
wan_hwifname=eth1
wan_proto=`config get wan_proto`

start() {
	# Start daemons.
	local igmp_enable=`config get wan_endis_igmp`
	killall igmpproxy
	if [ "$igmp_enable" = "0" ]; then	
		return $RETVAL
	fi
	echo $"Starting $prog: "
	echo "quickleave" > $CONFIG_FILE
	echo "mode 3" >> $CONFIG_FILE
	echo "" >> $CONFIG_FILE

        case "$wan_proto" in
                static|dhcp)
                        wan_ifname_upstream=$wan_ifname
                        ;;
                pppoe|pptp|l2tp)
                        wan_ifname_upstream=ppp0
                        ;;
                *)
                        wan_ifname_upstream=$wan_ifname
        esac
	
	echo "phyint $wan_ifname_upstream upstream  ratelimit 0  threshold 1" >> $CONFIG_FILE
	echo "" >> $CONFIG_FILE

	echo "phyint $lan_ifname downstream  ratelimit 0  threshold 1" >> $CONFIG_FILE
	echo "" >> $CONFIG_FILE

	if [ "$wan_ifname_upstream" = "$wan_hwifname" ]; then
		echo "phyint ppp0 disabled" >> $CONFIG_FILE
	echo "" >> $CONFIG_FILE
	fi

	touch $PID_FILE

	ebtables -A OUTPUT -o eth0.1 -p ipv4 --ip-dst 239.255.255.250 -j ACCEPT
	ebtables -A OUTPUT -o eth0.1 -p ipv4 --ip-dstrange 224.0.1.0-239.255.255.255 -j DROP

	echo 1 > /proc/igmpsnoop

	${prog} -c $CONFIG_FILE &
	RETVAL=$?
	echo
	return $RETVAL
}

stop() {
	# Stop daemons.
	echo $"Shutting down $prog: "
	killall igmpproxy
	rm -f ${PID_FILE}
	ebtables -D OUTPUT -o eth0.1 -p ipv4 --ip-dst 239.255.255.250 -j ACCEPT
        ebtables -D OUTPUT -o eth0.1 -p ipv4 --ip-dstrange 224.0.1.0-239.255.255.255 -j DROP
	RETVAL=$?
	echo
	return $RETVAL
}

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	RETVAL=$?
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $RETVAL

