#!/bin/sh

RAM_ROOT=/tmp/root

ldd() { LD_TRACE_LOADED_OBJECTS=1 $*; }
libs() { ldd $* | awk '{print $3}'; }

install_file() { # <file> [ <file> ... ]
	for file in "$@"; do
		dest="$RAM_ROOT/$file"
		[ -f $file -a ! -f $dest ] && {
			dir="$(dirname $dest)"
			mkdir -p "$dir"
			cp -af $file $dest
		}
	done
}

install_bin() { # <file> [ <symlink> ... ]
	src=$1
	files=$1
	[ -x "$src" ] && files="$src $(libs $src)"
	install_file $files
	shift
	for link in "$@"; do {
		dest="$RAM_ROOT/$link"
		dir="$(dirname $dest)"
		mkdir -p "$dir"
		[ -f "$dest" ] || ln -s $src $dest
	}; done
}

pivot() { # <new_root> <old_root>
	mount | grep "on $1 type" 2>&- 1>&- || mount -o bind $1 $1 && \
	mkdir -p $1$2 $1/proc $1/dev $1/tmp && \
	mount -o move /dev $1/dev && \
	mount -o move /proc $1/proc && \
	pivot_root $1 $1$2 || {
        	umount $1 $1
		return 1
	}
	mount -o move $2/tmp /tmp
	#mount -o move $2/jffs /jffs 2>&-
	return 0
}

run_ramfs() { # <command> [...]
	killall smbd proftpd afpd minidlna luns_scan.sh detcable send_wol set_fan_vol check_HDD_capacity
	sync
	sleep 4
	alldir=`cat /proc/mounts | grep sd | awk '{print $2}'`
	for dir in $alldir; do
		umount $dir
	done
	dd if=/dev/zero of=/tmp/tmp11 bs=17M count=1
	rm /tmp/tmp11 -rf
	install_bin /bin/busybox /usr/bin/killall5 /bin/sleep /bin/cat /sbin/ifconfig /bin/ash /bin/sh /bin/mount /bin/umount /sbin/pivot_root /sbin/reboot /bin/sync /bin/echo
	install_file /usr/sbin/net-cgi
	install_file /www/liteblue.gif /www/style/form.css /www/pls_wait.html /www/help.css /www/help.htm /www/upload.gif /www/funcs.js /www/UPG_process.htm /www/spacer.gif /www/menublue.gif /www/rbullet.gif /www/AUTO_upgrade_process.htm /www/upg_get_status.htm /www/image/tops.gif /www/top.js /www/image/wait30.gif /www/style/hijack_style.css /www/upgrade.cgi /www/top_nochange.html /www/image/buttons.gif /www/UPG_version.htm /www/upgrade.js /www/unauth.cgi /www/languages-en.js
	install_file /etc/resolv.conf 
	install_bin /lib/libcrypt-2.13.so /lib/libcrypt.so.1
	install_bin /lib/libc-2.13.so /lib/libc.so.6
	install_bin /lib/ld-2.13.so /lib/ld.so.1
	install_bin /lib/libm-2.13.so /lib/libm.so.6
	install_bin /lib/libpthread-2.13.so /lib/libpthread.so.0
	install_file /lib/libgcc_s.so.1
	install_file /usr/lib/libconfig.so
	install_file /usr/lib/libiconv.so /usr/lib/libiconv.so.2 /usr/lib/libiconv.so.2.4.0	

	pivot $RAM_ROOT /mnt || {
		echo "Failed to switch over to ramfs. Please reboot."
		exit 1
	}


	# spawn a new shell from ramdisk to reduce the probability of cache issues
	#exec /bin/busybox ash -c "$*"

}

run_ramfs

