#!/bin/sh /etc/rc.common

FIREWALL="/www/cgi-bin/firewall.sh"
RESOLV_CONF="/tmp/resolv.conf"
START=98

start() {
	if [ "$($CONFIG get ap_mode)" = "0" ]; then
		exit 0
	fi

	# Stop Traffic Meter
	/sbin/cmd_traffic_meter stop

	# Stop IPv6
	/etc/net6conf/net6conf stop

	# Stop basic WAN functions
	/etc/init.d/net-wan stop

	# Stop IPTV function
	/etc/init.d/net-iptv stop

	# Stop DHCP server
	killall udhcpd

	# Stop static route & ripd & LAN/WAN setup
	/sbin/cmdroute stop

	# Stop UPnP IGD
	/sbin/cmdupnp stop

	# Stop Auto IP (AP Mode)
	killall zcip

	# Block Services & Schedule
	/sbin/cmdsched

	# Stop DNS Proxy function
	/etc/init.d/dnsmasq stop

	# Stop Port Forwarding/Port Triggering & firewall & Remote Management
	$FIREWALL stop

	# Stop Dynamic DNS
	/sbin/cmd_ddns stop

	# Stop QOS
	/sbin/qos.sh stop

	# Add WAN interface to LAN bridge
	if [ "$WAN_IF" = "br1" ]; then
		brctl delif $WAN_IF $WAN_RAW_IF
		brctl addif $BR_IF $WAN_RAW_IF
	else
		brctl addif $BR_IF $WAN_IF
	fi

	# Restart Attach Device
	killall net-scan
	mkdir -p /tmp/netscan
	/usr/sbin/net-scan

	# Restart WLAN to let wireless client re-obtain IP address
	/sbin/wlan down
	/sbin/wlan up

	# Pull low PHY 9 seconds then pull high PHY to let wired client re-obtain IP address
	echo -n 9 > /proc/switch_phy

	# Static IP
	if [ "$($CONFIG get ap_ether_ip_assign)" = "0" ]; then
		local ori_ip=$(ifconfig $BR_IF | grep 'inet addr' | cut -f2 -d':' | cut -f1 -d' ')
		ifconfig $BR_IF 0.0.0.0
		ifconfig $BR_IF $($CONFIG get ap_ipaddr) netmask $($CONFIG get ap_netmask)
		route add default gw $($CONFIG get ap_gateway)
		$FIREWALL restart

		if [ "$($CONFIG get ap_ipaddr)" != "$ori_ip" ]; then
			# Restart DLNA
			/sbin/cmddlna ip_restart &
			# Restart samba
			/usr/bin/killall smbd
			/usr/sbin/update_smb
		fi

		echo "nameserver $($CONFIG get ap_ether_dns1)" > $RESOLV_CONF
		echo "nameserver $($CONFIG get ap_ether_dns2)" >> $RESOLV_CONF
	# DHCP
	else
		ifconfig $BR_IF 0.0.0.0
		/usr/sbin/restart_ap_udhcpc
	fi
	
	sleep 2
	
	# Start LLTD
	echo "$($CONFIG get ap_netbiosname)" > /proc/sys/kernel/hostname
	/usr/sbin/lld2d $($CONFIG get lan_ifname)
	/usr/sbin/brctl stp $BR_IF 1

	# Start NTP Client
	if [ "$($CONFIG get endis_ntp)" = "1" ]; then
		/usr/sbin/ntpclient
	fi

	/sbin/cmd_ebtables restart

	/etc/init.d/dnsmasq start

	# Start ReadySHARE Cloud
	/etc/init.d/leafp2p.sh start

	/sbin/cmdftp restart
}

stop() {
	killall udhcpc
	killall zcip

	if [ "$WAN_IF" = "br1" ]; then
		brctl delif $BR_IF $WAN_RAW_IF
		brctl addif $WAN_IF $WAN_RAW_IF
	else
		brctl delif $BR_IF $WAN_IF
	fi

	/usr/sbin/brctl stp $BR_IF 0

	# Start Traffic Meter
	/sbin/cmd_traffic_meter start

	/etc/init.d/net-lan restart
	/etc/init.d/net-wan restart
	/etc/init.d/init6 restart
	/etc/init.d/net-iptv restart

	# Restart WLAN to let wireless client re-obtain IP address
	/sbin/wlan down
	/sbin/wlan up

	/sbin/cmdftp restart

	# Pull low PHY 9 seconds then pull high PHY to let wired client re-obtain IP address
	# but this action has been done in /etc/init.d/net-lan restart, so, don't do again here.
}
