#!/bin/sh /etc/rc.common 
START=15

#
# Start the network....
#

start() {
	echo "Starting network..."
	/sbin/ifup -a
}

stop() {
	echo -n "Stopping network..."
	/sbin/ifdown -a
}

restart() {
	stop
	start
}
