#!/bin/sh /etc/rc.common
START=30

start() {
	local primary_server second_server

	[ "$($CONFIG get endis_ntp)" != "1" ] && exit
	primary_server=$($CONFIG get ntpserver1)
	second_server=$($CONFIG get ntpserver2)

	# Start NTP in net-wan script
	#ntpclient -h "$primary_server" -b "$second_server" -i 15 -m 60 -p 123 -s &
}

stop() {
	killall ntpclient
}

restart() {
	stop
	start
}
