#!/bin/sh
# Copyright (C) 2006 OpenWrt.org
export PATH=/bin:/sbin:/usr/bin:/usr/sbin

mount none /proc -t proc

mount -t sysfs sysfs /sys

size=$(awk '/MemTotal:/ {l=5242880;mt=($2*1024);print((s=mt/2)<l)?mt-l:s}' /proc/meminfo)
mount none /tmp -t tmpfs -o size=$size,nosuid,nodev,mode=1777

if grep devfs /proc/filesystems > /dev/null; then
	mount none /dev -t devfs
else
	mount -t tmpfs tmpfs /dev -o size=128K
	mknod /dev/console c 5 1
	mknod /dev/null  c 1 3
fi

mount none /proc/bus/usb -t usbfs

echo "- init -"

echo "" > /proc/sys/kernel/hotplug
	
exec /sbin/init
