#!/bin/sh

nvram=/bin/config
smtpc=/usr/sbin/ssmtp
LOG_FILE=/var/log/messages

# email related configs (in nvram get command) :
#   email_smtp        : smtp server address
#   email_endis_auth  : smtp sever needs authentication or not ?
#   email_username    : username for smtp server authentication
#   email_password    : password for smtp server authentication
#
#   email_addr        : "To addr", the addr of the receiver.
#   email_from_assign : assign "From addr" or not ?
#   email_this_addr   : "From addr", the addr the email (says itself) comes from.
#
#   email_notify      :
#   email_send_alert  :

tls_required() # $1: smtp_server
{
	# smtp.gmail.com requests TLS support
	echo $1 | grep -q 'gmail'
}

print_smtpc_conf()
{
	local smtp_server=$($nvram get email_smtp)

	echo "mailhub=$smtp_server"
	echo "FromLineOverride=yes"

	if [ $($nvram get email_endis_auth) = "1" ]; then
		echo "AuthUser=$($nvram get email_username)"
		echo "AuthPass=$($nvram get email_password)"

		if tls_required "$smtp_server"; then
			echo "UseTLS=YES"
			echo "UseSTARTTLS=YES"
		fi 
	fi
}

print_email_header()
{
	local hostname="$(cat /proc/sys/kernel/hostname)"
	local from
	local addr="$($nvram get email_addr)"

	# as I know, different smtp servers have different rules about "From addr" :
	# * dni : drops mails that "From addr" != "account email addr" silently.
	# * pchome : rejects sending mails that "From addr" != "account email addr".
	# * gmail : tranforms the "From addr" to "account email addr".
	# the smtp servers that don't care about "From addr" and just send mails are getting
	# scarce.
	if [ "$($nvram get email_from_assign)" = "1" ]; then
		from="\"root@$hostname\"<$($nvram get email_this_addr)>"
	else
		from="\"root@$hostname\"<$($nvram get email_addr)>"
	fi

	cat <<EOF
Subject: NETGEAR $hostname Log
From: $from
To: $addr

EOF
}

print_log()
{
	print_email_header

	if [ -s $LOG_FILE ]; then
		sed -n '1! G;$p;h' $LOG_FILE | sed -n '1,256 p'
	else
		echo "The system doesn't have any logs yet"
	fi
}

sendlog() # $1: clearlog_if_success
{
	local conf=/tmp/ssmtp.conf
	local email_file=/tmp/tmp_email_file
	local err_file=/tmp/tmp_email_err_file
	local addr="$($nvram get email_addr)"

	print_smtpc_conf > $conf
	print_log > $email_file
	if ! cat $email_file | $smtpc -C$conf $addr >/dev/null 2>$err_file; then
		logger -- "[email sent to: $addr]"
		logger -- "[email failed] $(cat $err_file)"
		rm -f $conf $email_file $err_file
		return 1
	fi
	rm -f $conf $email_file $err_file

	if [ "$1" = "clearlog_if_success" ]; then
		rm -f $LOG_FILE
	fi
	logger -- "[email sent to: $addr]"
	return 0
}

print_email_header_for_hdd()
{
	local hostname="$(cat /proc/sys/kernel/hostname)"
	local from
	local addr="$($nvram get email_addr)"

	if [ "$($nvram get email_from_assign)" = "1" ]; then
		from="\"root@$hostname\"<$($nvram get email_this_addr)>"
	else
		from="\"root@$hostname\"<$($nvram get email_addr)>"
	fi

	cat <<EOF
Subject: Warning!WNDR4700 Internal HDD might have some issues
From: $from
To: $addr

EOF
}

print_hdd_log()
{
	print_email_header_for_hdd
	echo "[HDD ERROR] Warning! The internal hard drive have the reallocated sector error frequently, we suggest you to replace the internal hard drive now."
}

# per NTGR's requirement, when the internal disk have something wrong, we need to email to the user ath 9:30 AM.
email_HDD_err_log()
{
	local conf=/tmp/hdd_err.conf
	local email_file=/tmp/tmp_hdd_email.file
	local err_file=/tmp/tmp_hdd_err_email.file
	local addr="$($nvram get email_addr)"

	echo "email_HDD_err_log in ..." > /dev/console
	print_smtpc_conf > $conf
	print_hdd_log > $email_file
	if ! cat $email_file | $smtpc -C$conf $addr >/dev/null 2>$err_file; then
		logger -- "[email sent to: $addr]"
		logger -- "[email failed] $(cat $err_file)"
		rm -f $conf $email_file $err_file
		return 1
	fi
	rm -f $conf $email_file $err_file
	logger -- "[email sent to: $addr]"
	return 0

}

### start here ###

prog=${0##*/}

case "$prog" in
email_log)
	[ $($nvram get email_notify) = "0" ] && exit
	sendlog "clearlog_if_success"
	;;
email_full_log)
	[ $($nvram get email_notify) = "0" ] && exit
	# send log only if lines of log file > 256 * 90% = 230.4
	[ ! -s $LOG_FILE ] && exit
	[ "$(wc -l $LOG_FILE | sed -n 's/[^0-9]*//gp')" -le "230" ] && exit
	sendlog "clearlog_if_success"
	;;
send_email_alert)
	[ $($nvram get email_notify) = "0" ] && exit
	[ "$($nvram get email_send_alert)" = "0" ] && exit
	sendlog "clearlog_if_success"
	;;
send_log)
	sendlog
	;;
email_HDD_err_log)
	[ $($nvram get email_notify) = "0" ] && exit
	email_HDD_err_log
	;;
esac

